services:
  clipboard-sync-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - DB_PATH=data/clipboard.db
      - MAX_CONTENT_SIZE=1048576
      - RATE_LIMIT_RPS=100
      - CORS_ALLOW_ORIGINS=*
    volumes:
      - ./data:/root/data
      - ./logs:/root/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - clipboard-network

  # 反向代理服务器
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      clipboard-sync-server:
        condition: service_healthy
    networks:
      - clipboard-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      - TZ=Asia/Shanghai

networks:
  clipboard-network:
    driver: bridge

volumes:
  clipboard_data:
  clipboard_logs: