services:
  clipboard-sync-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRE_HOUR=24
      - DB_PATH=data/clipboard.db
      - DB_DEBUG=false
      - MAX_CONTENT_SIZE=1048576
      - RATE_LIMIT_RPS=100
      - CORS_ALLOW_ORIGINS=*
      - LOG_LEVEL=info
      - LOG_FILE=logs/server.log
      - CLEANUP_DAYS=30
      - ENABLE_CLEANUP=true
      - CLEANUP_INTERVAL=24h
    volumes:
      # 使用 Docker 命名卷而不是绑定挂载，避免权限问题
      - clipboard_data:/app/data
      - clipboard_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - clipboard-network

networks:
  clipboard-network:
    driver: bridge

volumes:
  clipboard_data:
    driver: local
  clipboard_logs:
    driver: local